apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# patches:
#   - target:
#       kind: HelmRelease
#     patch: |-
#       - op: replace
#         path: /metadata/name
#         value: podinfo-2-prod
#       - op: replace
#         path: /spec/releaseName
#         value: podinfo-2-prod
      