---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-1-rc
  namespace: flux-system
spec:
  interval: 10m0s
  # dependsOn:
  #   - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/podinfo-1-rc/west
  prune: true
  wait: true
  timeout: 5m0s